version: "3.7"
services:

  frontend:
    container_name: frontend
    image: releasepraqma/todo-frontend
    build:
      context: ../frontend
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    environment:
      - BACKEND_HOST=todo-backend
      - BACKEND_PORT=8080

  todo-backend:
    container_name: backend
    image: releasepraqma/todo-backend
    build:
      context: ../
      dockerfile: ./build/package/Dockerfile
    ports:
      - 8902:8080
    environment:
      - TODO_DATABASEHOST=todo-backend-db
      - TODO_DATABASEPORT=5432
      - TODO_DATABASEUSERNAME=todo
      - TODO_DATABASEPASSWORD=todo
      - TODO_DATABASESCHEMA=todo
      # - TODO_URL=http://todo-backend:8080
      - TODO_URL=http://localhost/todo
    depends_on:
      - todo-backend-db

  todo-backend-db:
    container_name: db
    # image: "postgres:12"
    image: bitnami/postgresql:12
    ports:
      - 54321:5432
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=todo
      - POSTGRES_PASSWORD=todo
