apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: backend-db
  name: backend-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend-db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: backend-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: {{ .Values.db.dbName }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.dbPassword }}
            - name: POSTGRES_USER
              value: {{ .Values.db.dbUsername }}
          image: bitnami/postgresql:12
          name: db
          ports:
            - containerPort: 5432
          resources: {}
      restartPolicy: Always
status: {}
