apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: TODO_DATABASEHOST
              value: {{ .Values.backend.dbHost }}
            - name: TODO_DATABASEPORT
              value: {{ .Values.backend.dbPort | quote }}
            - name: TODO_DATABASEUSERNAME
              value: {{ .Values.backend.dbUsername }}
            - name: TODO_DATABASEPASSWORD
              value: {{ .Values.backend.dbPassword }}
            - name: TODO_DATABASESCHEMA
              value: {{ .Values.backend.dbSchema }}
            - name: TODO_URL
              value: {{ .Values.backend.backendURL }}
          image: releasepraqma/todo-backend
          name: backend
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
