apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
      nodePort: 32123
  selector:
    io.kompose.service: frontend
  type: {{ .Values.frontend.type }}
status:
  loadBalancer: {}
