apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: todo-backend
  name: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: todo-backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: todo-backend
    spec:
      containers:
        - env:
            - name: TODO_DATABASEHOST
              value: todo-backend-db
            - name: TODO_DATABASEPASSWORD
              value: todo
            - name: TODO_DATABASEPORT
              value: "5432"
            - name: TODO_DATABASESCHEMA
              value: todo
            - name: TODO_DATABASEUSERNAME
              value: todo
            - name: TODO_URL
              value: http://localhost/todo
          image: releasepraqma/todo-backend
          name: backend
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
