apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: todo-backend
  name: todo-backend
spec:
  ports:
    - name: "8902"
      port: 8902
      targetPort: 8080
  selector:
    io.kompose.service: todo-backend
status:
  loadBalancer: {}
